name: Tassk Form
description: A task form with different fields
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Implement the missing code for ...
      value: "Implement the missing code for ..."
    validations:
      required: false

  - type: textarea
    id: actions
    attributes:
      label: Actions
    validations:
      required: false

  - type: dropdown
    id: estimate
    attributes:
      label: Estimate
      options:
        - small
        - medium
        - long
    validations:
      required: false

  - type: textarea
    id: Tests
    attributes:
      label: Tests
      placeholder: Unit tests (in `./logic/logic/test/propositions/test_syntax.py`)
      value: "Unit tests (in `./logic/logic/test/propositions/test_syntax.py`)"
    validations:
      required: false